data = [
    ['In the cult favorite, Tom and Jerry, Tom\'s eyes are of which color?',
     'Blue',
     'Red',
     'Green',
     'Yellow',
     4], 
    ['Which social media app was originally called Pikaboo?',
     'Snapchat',
     'Instagram',
     'X',
     'Tinder',
     1], 
    ['What runs around a whole yard without moving',
     'A Tree',
     'Fence',
     'A Car',
     'A Flower',
     2], 
    ['Which fast food restaurant has the largest number of retail locations in the world?',
     'Dmonios',
     'Chipotle',
     'Subway',
     'MacDonald\'s',
     3], 
    ['From which country did French fries originate',
     'USA',
     'France',
     'Belgium',
     'UK',
    3],
    ['Which is the only body part that is fully grown from birth?',
     'Lips',
     'Ears',
     'Nose',
     'Eyes',
    4],
    ['The more you take, the more you leave behind. What am I?',
     'Footsteps',
     'Shadow',
     'Time',
     'Memories',
    1],
    [' What comes once in a minute, twice in a moment, but never in a thousand years?',
     'A shooting star',
     'The number 1',
     'A blink',
     'The letter M',
    4],
    [' What was the original name of Facebook before it was rebranded?',
     'The Facebook',
     'Facemash',
     'MySpace',
     'Friendster',
    2],
    ['What is the dog’s name in the series “Tom and Jerry”?',
     'Bingo',
     'Mello',
     'Charlie',
     'Spike',
    4],
    ]