data_me = [
    ['Which is the largest planet in our solar system',
     'Earth',
     'Mars',
     'Saturn',
     'Jupiter',
     4], 
    ['Which is the first animal to go to space?',
     'Laika',
     'Putin',
     'Nikola',
     'Jumbo',
     1], 
    ['GDSC Thapar founded at',
     '1800',
     '1900',
     '2000',
     '2024',
     2], 
    ['Who loves to play milk choco',
     'me',
     'you',
     'all',
     'none',
     3], 
    ['Who does Nobita marry with?',
     'Zaiko',
     'Shizuka',
     'Nobiki',
     'Maria',
     2]
]